Write tests for contracts/omen/OMNGuild.sol
AugustoL/dxdao-contracts pull request #31
Opened 2021-05-03 16:48 UTC by kermit4

2021-05-03 17:57 UTC, AugustoL requested changes

2021-05-03 17:57 UTC, AugustoL commented on contracts/omen/OMNGuild.sol
> +import "hardhat/console.sol";
lets remove the console import. We dont want it in the production deployment.

2021-05-03 17:57 UTC, AugustoL commented on contracts/omen/OMNGuild.sol
> +        require(votesOf(msg.sender) >= getVotesForCreation(), "OMNGuild: Not enough tokens to create proposal");   // I.B.2.c
whats `// I.B.2.c`? in the comment? lets remove it?

2021-05-03 17:57 UTC, AugustoL commented on contracts/omen/OMNGuild.sol
> +        require(proposals[marketValidationProposals[proposalsForMarketValidation[proposalId]].marketValid].votes[msg.sender] == 0, "OMNGuild: Already voted");
wouldnt this fail in a proposal that is not related with market validation?

2021-05-03 18:11 UTC, kermit4 commented on contracts/omen/OMNGuild.sol
> +        require(votesOf(msg.sender) >= getVotesForCreation(), "OMNGuild: Not enough tokens to create proposal");   // I.B.2.c
It's referencing the sections from spec.

2021-05-03 18:19 UTC, kermit4 commented on contracts/omen/OMNGuild.sol
> +        require(proposals[marketValidationProposals[proposalsForMarketValidation[proposalId]].marketValid].votes[msg.sender] == 0, "OMNGuild: Already voted");
I didn't think of that, but, would it?  I thought in Solidity everything defaulted to null/zero anyway?

2021-05-03 18:31 UTC, kermit4 commented on contracts/omen/OMNGuild.sol
> +        require(proposals[marketValidationProposals[proposalsForMarketValidation[proposalId]].marketValid].votes[msg.sender] == 0, "OMNGuild: Already voted");
I put "       require(proposals[proposalIds[i]].votes[msg.sender] == 0, "OMNGuild: Already voted");
" back

I had to do a force push so it doesn't show up above because it looks like I merged without squashing the commits which you prefer be done prior to your merge, if I'm understanding correctly.

2021-05-04 01:26 UTC, AugustoL commented on contracts/omen/OMNGuild.sol
> +        require(votesOf(msg.sender) >= getVotesForCreation(), "OMNGuild: Not enough tokens to create proposal");   // I.B.2.c
Ok, just remove it for now, or add a comment in the function that `getVotesForCreation()` amount fo votes are required to create a proposal, it will be more clear.

2021-05-04 01:32 UTC, AugustoL commented on contracts/omen/OMNGuild.sol
> +        require(votesOf(msg.sender) >= getVotesForCreation(), "OMNGuild: Not enough tokens to create proposal");   // I.B.2.c
Ok, just remove it for now, or add a comment in the function that `getVotesForCreation()` amount fo votes are required to create a proposal, it will be more clear.

2021-05-04 01:34 UTC, merged